### ISSUE TITLE
Why can’t I get typical brain topographic maps in a microstate analysis?

### ISSUE THREAD

**Issue by nylsp** [vferat/pycrostates#174]
As everyone knows, there are four archetypal microstates in normal people that explain most of the global topographic variance. These four maps have right-frontal left-posterior, left-frontal right-posterior, midline frontal-occipital, and midline frontal topographies, and are labeled A, B, C, and D. However, I cannot get typical topographic maps when I compute EEG microstates in subject level. Some are close to the typical map, and some are very different. I wonder if there is any criterion to tell me the result is acceptable or not. I found that the atypical subject can influence group-level analysis.

**Comment by vferat** [comment]
Hey @nylsp,

Generally speaking, the pre-processing stages have a fairly significant impact on the topographies of the microstates. In particular, the presence of artefacts such as eye blinks, muscle contractions, etc...
Could you attach a figure of the topographies that you consider abnormal, in order to have a more precise idea of the sources of these anomalies?
It's also possible not to have the canonical maps, depending on the population and conditions studied...

**Comment by mscheltienne** [comment]
@vferat See: https://mne.discourse.group/t/why-cant-i-get-typical-brain-topographic-maps-in-a-microstate-analysis/8716

**Comment by mscheltienne** [comment]
Closing as this was moved to the MNE Discourse.
